/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Classes.Categoria;
import Classes.Fornecedor;
import Classes.Produto;
import Connection.DAOFactory;
import DAO.SqliteCategoriaDAO;
import DAO.SqliteFornecedorDAO;
import DAO.SqliteProdutoDAO;
import Interfaces.CategoriaDAO;
import Interfaces.FornecedorDAO;
import Interfaces.ProdutoDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author igor_
 */
public class Principal extends javax.swing.JFrame {
    
    public DAOFactory factory = DAOFactory.getDAOFactory(DAOFactory.SQLITE);
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tbl_produtos.getModel();
        DefaultTableModel categoria = (DefaultTableModel) tbl_categorias.getModel();
        DefaultTableModel fornecedor = (DefaultTableModel) tbl_fornecedores.getModel();
        tbl_produtos.setRowSorter(new TableRowSorter(modelo));
        tbl_categorias.setRowSorter(new TableRowSorter(categoria));
        tbl_fornecedores.setRowSorter(new TableRowSorter(fornecedor));
        
        readJTable();
        readJTableCat();
        readJTableFor();
        
        btn_pro_salvar.setEnabled(false);
        btn_pro_cancelar.setEnabled(false);
        btn_pro_editar.setEnabled(false);
        btn_pro_excluir.setEnabled(false);
        btn_cat_salvar.setEnabled(false);
        btn_cat_cancelar.setEnabled(false);
        btn_cat_editar.setEnabled(false);
        btn_cat_excluir.setEnabled(false);
        btn_for_salvar.setEnabled(false);
        btn_for_cancelar.setEnabled(false);
        btn_for_editar.setEnabled(false);
        btn_for_excluir.setEnabled(false);
        c_pro_nome.setEnabled(false);
        c_pro_categoria.setEnabled(false);
        c_pro_fornecedor.setEnabled(false);
        c_cat_nome.setEnabled(false);
        c_cat_des.setEnabled(false);
        c_for_nome.setEnabled(false);
        c_for_endereco.setEnabled(false);
        c_for_cidade.setEnabled(false);
        c_for_telefone.setEnabled(false);
        
        SqliteCategoriaDAO cdao = new SqliteCategoriaDAO();
        
        for(Categoria c: cdao.read()){
            c_pro_categoria.addItem(c);
        }
        
        SqliteFornecedorDAO fdao = new SqliteFornecedorDAO();
        
        for(Fornecedor f: fdao.read()){
            c_pro_fornecedor.addItem(f);
        }
    }
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) tbl_produtos.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = factory.getProdutoDAO();
        
        for(Produto p: pdao.read()){
            
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getCategoria_id(),
                p.getFornecedor_id()
            });
            
        }
    }
    
    public void readJTableCat(){
        DefaultTableModel categoria = (DefaultTableModel) tbl_categorias.getModel();
        categoria.setNumRows(0);
        CategoriaDAO cdao = factory.getCategoriaDAO();
        
        for(Categoria c: cdao.read()){
            
            categoria.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getDescricao()
            });
            
        }
    }
    
    public void readJTableFor(){
        DefaultTableModel fornecedor = (DefaultTableModel) tbl_fornecedores.getModel();
        fornecedor.setNumRows(0);
        FornecedorDAO fdao = factory.getFornecedorDAO();
        
        for(Fornecedor f: fdao.read()){
            
            fornecedor.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getEndereco(),
                f.getCidade(),
                f.getTelefone()
            });
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_produtos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        c_pro_nome = new javax.swing.JTextField();
        btn_pro_salvar = new javax.swing.JButton();
        btn_pro_cancelar = new javax.swing.JButton();
        btn_pro_editar = new javax.swing.JButton();
        c_pro_categoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c_pro_fornecedor = new javax.swing.JComboBox<>();
        btn_pro_novo = new javax.swing.JButton();
        btn_pro_excluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_categorias = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        c_cat_nome = new javax.swing.JTextField();
        btn_cat_salvar = new javax.swing.JButton();
        btn_cat_cancelar = new javax.swing.JButton();
        btn_cat_editar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        c_cat_des = new javax.swing.JTextField();
        btn_fun_novo = new javax.swing.JButton();
        btn_cat_excluir = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_fornecedores = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        c_for_nome = new javax.swing.JTextField();
        btn_for_salvar = new javax.swing.JButton();
        btn_for_cancelar = new javax.swing.JButton();
        btn_for_editar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        c_for_endereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        c_for_cidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        c_for_telefone = new javax.swing.JTextField();
        btn_for_novo = new javax.swing.JButton();
        btn_for_excluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Categoria", "Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_produtosMouseClicked(evt);
            }
        });
        tbl_produtos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_produtosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_produtos);
        if (tbl_produtos.getColumnModel().getColumnCount() > 0) {
            tbl_produtos.getColumnModel().getColumn(0).setMinWidth(40);
            tbl_produtos.getColumnModel().getColumn(0).setPreferredWidth(1);
            tbl_produtos.getColumnModel().getColumn(0).setMaxWidth(40);
            tbl_produtos.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbl_produtos.getColumnModel().getColumn(2).setPreferredWidth(50);
            tbl_produtos.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(null), null));
        jPanel3.setToolTipText("Cadastro de Produtos");
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("Nome: ");

        c_pro_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_pro_nomeActionPerformed(evt);
            }
        });

        btn_pro_salvar.setText("Salvar");
        btn_pro_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pro_salvarActionPerformed(evt);
            }
        });

        btn_pro_cancelar.setText("Cancelar");
        btn_pro_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pro_cancelarActionPerformed(evt);
            }
        });

        btn_pro_editar.setText("Atualizar");
        btn_pro_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pro_editarActionPerformed(evt);
            }
        });

        jLabel1.setText("Categoria:");

        jLabel3.setText("Fornecedor:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(c_pro_nome))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_pro_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(btn_pro_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_pro_cancelar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(c_pro_categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c_pro_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(c_pro_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(c_pro_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(c_pro_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pro_editar)
                    .addComponent(btn_pro_salvar)
                    .addComponent(btn_pro_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_pro_novo.setText("Novo");
        btn_pro_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pro_novoActionPerformed(evt);
            }
        });

        btn_pro_excluir.setText("Excluir");
        btn_pro_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pro_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_pro_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_pro_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pro_novo)
                    .addComponent(btn_pro_excluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Produtos", jPanel1);

        tbl_categorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categoria", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_categorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_categoriasMouseClicked(evt);
            }
        });
        tbl_categorias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_categoriasKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_categorias);
        if (tbl_categorias.getColumnModel().getColumnCount() > 0) {
            tbl_categorias.getColumnModel().getColumn(0).setMinWidth(40);
            tbl_categorias.getColumnModel().getColumn(0).setPreferredWidth(1);
            tbl_categorias.getColumnModel().getColumn(0).setMaxWidth(40);
            tbl_categorias.getColumnModel().getColumn(1).setPreferredWidth(30);
            tbl_categorias.getColumnModel().getColumn(2).setPreferredWidth(220);
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(null), null));

        jLabel4.setText("Nome: ");

        btn_cat_salvar.setText("Salvar");
        btn_cat_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cat_salvarActionPerformed(evt);
            }
        });

        btn_cat_cancelar.setText("Cancelar");
        btn_cat_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cat_cancelarActionPerformed(evt);
            }
        });

        btn_cat_editar.setText("Atualizar");
        btn_cat_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cat_editarActionPerformed(evt);
            }
        });

        jLabel8.setText("Descrição:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_cat_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(btn_cat_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cat_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_cat_nome)
                            .addComponent(c_cat_des))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(c_cat_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(c_cat_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cat_cancelar)
                    .addComponent(btn_cat_salvar)
                    .addComponent(btn_cat_editar))
                .addContainerGap())
        );

        btn_fun_novo.setText("Novo");
        btn_fun_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fun_novoActionPerformed(evt);
            }
        });

        btn_cat_excluir.setText("Excluir");
        btn_cat_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cat_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_fun_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cat_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cat_excluir)
                    .addComponent(btn_fun_novo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Categorias", jPanel2);

        tbl_fornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Endereço", "Cidade", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_fornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_fornecedoresMouseClicked(evt);
            }
        });
        tbl_fornecedores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_fornecedoresKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_fornecedores);
        if (tbl_fornecedores.getColumnModel().getColumnCount() > 0) {
            tbl_fornecedores.getColumnModel().getColumn(0).setMinWidth(40);
            tbl_fornecedores.getColumnModel().getColumn(0).setPreferredWidth(1);
            tbl_fornecedores.getColumnModel().getColumn(0).setMaxWidth(40);
            tbl_fornecedores.getColumnModel().getColumn(1).setPreferredWidth(30);
            tbl_fornecedores.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(null), null));

        jLabel5.setText("Nome: ");

        btn_for_salvar.setText("Salvar");
        btn_for_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_for_salvarActionPerformed(evt);
            }
        });

        btn_for_cancelar.setText("Cancelar");
        btn_for_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_for_cancelarActionPerformed(evt);
            }
        });

        btn_for_editar.setText("Atualizar");
        btn_for_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_for_editarActionPerformed(evt);
            }
        });

        jLabel6.setText("Endereço:");

        jLabel9.setText("Cidade:");

        jLabel10.setText("Telefone:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btn_for_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(btn_for_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_for_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_for_endereco)
                            .addComponent(c_for_nome)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(c_for_cidade)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_for_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(c_for_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(c_for_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(c_for_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(c_for_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_for_cancelar)
                    .addComponent(btn_for_salvar)
                    .addComponent(btn_for_editar))
                .addContainerGap())
        );

        btn_for_novo.setText("Novo");
        btn_for_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_for_novoActionPerformed(evt);
            }
        });

        btn_for_excluir.setText("Excluir");
        btn_for_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_for_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_for_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_for_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_for_novo)
                    .addComponent(btn_for_excluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Fornecedores", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cat_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cat_excluirActionPerformed
        if(tbl_categorias.getSelectedRow() != -1){
            Categoria c = new Categoria();
            CategoriaDAO cdao = factory.getCategoriaDAO();

            c.setId((int)tbl_categorias.getValueAt(tbl_categorias.getSelectedRow(), 0));

            cdao.delete(c);

            //c_fun_departamento.setText("");
            c_cat_nome.setText("");
            c_cat_des.setText("");

            readJTableCat();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma categoria para ser excluída!");
        }

        btn_fun_novo.setEnabled(true);
        btn_cat_salvar.setEnabled(false);
        btn_cat_cancelar.setEnabled(false);
        btn_cat_editar.setEnabled(false);
        btn_cat_excluir.setEnabled(false);
        c_cat_nome.setEnabled(false);
        c_cat_des.setEnabled(false);
    }//GEN-LAST:event_btn_cat_excluirActionPerformed

    private void btn_fun_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fun_novoActionPerformed
        c_cat_nome.setText("");

        btn_cat_salvar.setEnabled(true);
        btn_cat_cancelar.setEnabled(true);
        btn_cat_editar.setEnabled(false);
        c_cat_nome.setEnabled(true);
        c_cat_des.setEnabled(true);
    }//GEN-LAST:event_btn_fun_novoActionPerformed

    private void btn_cat_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cat_editarActionPerformed
        if(tbl_categorias.getSelectedRow() != -1){
            Categoria c = new Categoria();
            CategoriaDAO cdao = factory.getCategoriaDAO();
            
            c.setNome(c_cat_nome.getText());
            c.setDescricao(c_cat_des.getText());
            c.setId((int)tbl_categorias.getValueAt(tbl_categorias.getSelectedRow(), 0));

            cdao.update(c);

            //c_fun_departamento.setText("");
            c_cat_nome.setText("");
            c_cat_des.setText("");

            readJTableCat();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma categoria para ser editada!");
        }

        btn_fun_novo.setEnabled(true);
        btn_cat_editar.setEnabled(false);
        btn_cat_excluir.setEnabled(false);
        btn_cat_cancelar.setEnabled(false);
        c_cat_nome.setEnabled(false);
        c_cat_des.setEnabled(false);

    }//GEN-LAST:event_btn_cat_editarActionPerformed

    private void btn_cat_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cat_cancelarActionPerformed
        btn_cat_salvar.setEnabled(false);
        btn_cat_cancelar.setEnabled(false);
        btn_fun_novo.setEnabled(true);
        btn_cat_editar.setEnabled(false);
        btn_cat_excluir.setEnabled(false);
        c_cat_nome.setEnabled(false);
        c_cat_des.setEnabled(false);
    }//GEN-LAST:event_btn_cat_cancelarActionPerformed

    private void btn_cat_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cat_salvarActionPerformed
        Categoria c = new Categoria();
        CategoriaDAO cdao = factory.getCategoriaDAO();
        c.setNome(c_cat_nome.getText());
        c.setDescricao(c_cat_des.getText());

        cdao.create(c);

        //c_fun_departamento.setText("");
        c_cat_nome.setText("");
        c_cat_des.setText("");

        readJTableCat();

        btn_cat_salvar.setEnabled(false);
        btn_cat_cancelar.setEnabled(false);
        btn_cat_editar.setEnabled(false);
        c_cat_nome.setEnabled(false);
        c_cat_des.setEnabled(false);

    }//GEN-LAST:event_btn_cat_salvarActionPerformed

    private void tbl_categoriasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_categoriasKeyReleased
        if(tbl_categorias.getSelectedRow() != -1){
            c_cat_nome.setText(tbl_categorias.getValueAt(tbl_categorias.getSelectedRow(), 1).toString());
            c_cat_des.setText(tbl_categorias.getValueAt(tbl_categorias.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_tbl_categoriasKeyReleased

    private void tbl_categoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_categoriasMouseClicked
        if(tbl_categorias.getSelectedRow() != -1){
            c_cat_nome.setText(tbl_categorias.getValueAt(tbl_categorias.getSelectedRow(), 1).toString());
            c_cat_des.setText(tbl_categorias.getValueAt(tbl_categorias.getSelectedRow(), 2).toString());
        }

        btn_fun_novo.setEnabled(false);
        btn_cat_editar.setEnabled(true);
        btn_cat_excluir.setEnabled(true);
        btn_cat_cancelar.setEnabled(true);
        c_cat_nome.setEnabled(true);
        c_cat_des.setEnabled(true);
    }//GEN-LAST:event_tbl_categoriasMouseClicked

    private void btn_pro_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pro_excluirActionPerformed
        if(tbl_produtos.getSelectedRow() != -1){
            Produto p = new Produto();
            ProdutoDAO pdao = factory.getProdutoDAO();

            p.setId((int)tbl_produtos.getValueAt(tbl_produtos.getSelectedRow(), 0));

            pdao.delete(p);

            c_pro_nome.setText("");

            readJTable();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto para ser excluído!");
        }

        c_pro_nome.setEnabled(false);
        btn_pro_salvar.setEnabled(false);
        btn_pro_cancelar.setEnabled(false);
        btn_pro_editar.setEnabled(false);
        btn_pro_excluir.setEnabled(false);
        btn_pro_novo.setEnabled(true);
    }//GEN-LAST:event_btn_pro_excluirActionPerformed

    private void btn_pro_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pro_novoActionPerformed
        c_pro_nome.setText("");

        btn_pro_salvar.setEnabled(true);
        btn_pro_cancelar.setEnabled(true);
        c_pro_nome.setEnabled(true);
        c_pro_categoria.setEnabled(true);
        c_pro_fornecedor.setEnabled(true);
        btn_pro_editar.setEnabled(false);
    }//GEN-LAST:event_btn_pro_novoActionPerformed

    private void btn_pro_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pro_editarActionPerformed
        if(tbl_produtos.getSelectedRow() != -1){
            Produto p = new Produto();
            ProdutoDAO pdao = factory.getProdutoDAO();
            Categoria jbox_cat = (Categoria) c_pro_categoria.getSelectedItem();
            Fornecedor jbox_for = (Fornecedor) c_pro_fornecedor.getSelectedItem();
            
            p.setNome(c_pro_nome.getText());
            p.setCategoria_id(jbox_cat.getId());
            p.setFornecedor_id(jbox_for.getId());
            
            p.setId((int)tbl_produtos.getValueAt(tbl_produtos.getSelectedRow(), 0));

            pdao.update(p);

            c_pro_nome.setText("");

            readJTable();

            btn_pro_excluir.setEnabled(false);
            btn_pro_editar.setEnabled(false);
            btn_pro_cancelar.setEnabled(false);
            c_pro_nome.setEnabled(false);

        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto para ser editado!");
        }
    }//GEN-LAST:event_btn_pro_editarActionPerformed

    private void btn_pro_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pro_cancelarActionPerformed
        btn_pro_novo.setEnabled(true);
        btn_pro_salvar.setEnabled(false);
        btn_pro_cancelar.setEnabled(false);
        btn_pro_editar.setEnabled(false);
        btn_pro_excluir.setEnabled(false);
        c_pro_nome.setEnabled(false);
        c_pro_categoria.setEnabled(false);
        c_pro_fornecedor.setEnabled(false);
    }//GEN-LAST:event_btn_pro_cancelarActionPerformed

    private void btn_pro_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pro_salvarActionPerformed
        Produto p = new Produto();
        ProdutoDAO pdao = factory.getProdutoDAO();
        Categoria jbox_cat = (Categoria) c_pro_categoria.getSelectedItem();
        Fornecedor jbox_for = (Fornecedor) c_pro_fornecedor.getSelectedItem();
        
        p.setNome(c_pro_nome.getText());
        p.setCategoria_id(jbox_cat.getId());
        p.setFornecedor_id(jbox_for.getId());

        pdao.create(p);

        c_pro_nome.setText("");

        readJTable();

        btn_pro_salvar.setEnabled(false);
        btn_pro_cancelar.setEnabled(false);
        btn_pro_editar.setEnabled(false);
        btn_pro_excluir.setEnabled(false);
        c_pro_nome.setEnabled(false);
    }//GEN-LAST:event_btn_pro_salvarActionPerformed

    private void c_pro_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_pro_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_pro_nomeActionPerformed

    private void tbl_produtosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_produtosKeyReleased
        if(tbl_produtos.getSelectedRow() != -1){
            c_pro_nome.setText(tbl_produtos.getValueAt(tbl_produtos.getSelectedRow(), 1).toString());
            c_pro_categoria.setSelectedItem(tbl_produtos.getValueAt(tbl_produtos.getSelectedRow(), 2).toString());
            c_pro_fornecedor.setSelectedItem(tbl_produtos.getValueAt(tbl_produtos.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_tbl_produtosKeyReleased

    private void tbl_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_produtosMouseClicked
        if(tbl_produtos.getSelectedRow() != -1){
            c_pro_nome.setText(tbl_produtos.getValueAt(tbl_produtos.getSelectedRow(), 1).toString());
            c_pro_categoria.setSelectedItem(tbl_produtos.getValueAt(tbl_produtos.getSelectedRow(), 2).toString());
            c_pro_fornecedor.setSelectedItem(tbl_produtos.getValueAt(tbl_produtos.getSelectedRow(), 3).toString());
        }

        c_pro_nome.setEnabled(true);
        c_pro_categoria.setEnabled(true);
        c_pro_fornecedor.setEnabled(true);
        btn_pro_editar.setEnabled(true);
        btn_pro_cancelar.setEnabled(true);
        btn_pro_excluir.setEnabled(true);
        btn_pro_novo.setEnabled(false);
    }//GEN-LAST:event_tbl_produtosMouseClicked

    private void tbl_fornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_fornecedoresMouseClicked
        if(tbl_fornecedores.getSelectedRow() != -1){
            c_for_nome.setText(tbl_fornecedores.getValueAt(tbl_fornecedores.getSelectedRow(), 1).toString());
            c_for_endereco.setText(tbl_fornecedores.getValueAt(tbl_fornecedores.getSelectedRow(), 2).toString());
            c_for_cidade.setText(tbl_fornecedores.getValueAt(tbl_fornecedores.getSelectedRow(), 3).toString());
            c_for_telefone.setText(tbl_fornecedores.getValueAt(tbl_fornecedores.getSelectedRow(), 4).toString());
        }
        
        c_for_nome.setEnabled(true);
        c_for_endereco.setEnabled(true);
        c_for_cidade.setEnabled(true);
        c_for_telefone.setEnabled(true);
        btn_for_editar.setEnabled(true);
        btn_for_cancelar.setEnabled(true);
        btn_for_excluir.setEnabled(true);
        btn_for_novo.setEnabled(false);
    }//GEN-LAST:event_tbl_fornecedoresMouseClicked

    private void tbl_fornecedoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_fornecedoresKeyReleased
        if(tbl_fornecedores.getSelectedRow() != -1){
            c_for_nome.setText(tbl_fornecedores.getValueAt(tbl_fornecedores.getSelectedRow(), 1).toString());
            c_for_endereco.setText(tbl_fornecedores.getValueAt(tbl_fornecedores.getSelectedRow(), 2).toString());
            c_for_cidade.setText(tbl_fornecedores.getValueAt(tbl_fornecedores.getSelectedRow(), 3).toString());
            c_for_telefone.setText(tbl_fornecedores.getValueAt(tbl_fornecedores.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_tbl_fornecedoresKeyReleased

    private void btn_for_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_for_salvarActionPerformed
        Fornecedor f = new Fornecedor();
        FornecedorDAO fdao = factory.getFornecedorDAO();
        
        f.setNome(c_for_nome.getText());
        f.setEndereco(c_for_endereco.getText());
        f.setCidade(c_for_cidade.getText());
        f.setTelefone(c_for_telefone.getText());

        fdao.create(f);

        c_for_nome.setText("");
        c_for_endereco.setText("");
        c_for_cidade.setText("");
        c_for_telefone.setText("");

        readJTableFor();

        btn_for_salvar.setEnabled(false);
        btn_for_cancelar.setEnabled(false);
        btn_for_editar.setEnabled(false);
        btn_for_excluir.setEnabled(false);
        c_for_nome.setEnabled(false);
        c_for_endereco.setEnabled(false);
        c_for_cidade.setEnabled(false);
        c_for_telefone.setEnabled(false);
    }//GEN-LAST:event_btn_for_salvarActionPerformed

    private void btn_for_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_for_cancelarActionPerformed
        btn_for_novo.setEnabled(true);
        btn_for_salvar.setEnabled(false);
        btn_for_cancelar.setEnabled(false);
        btn_for_editar.setEnabled(false);
        btn_for_excluir.setEnabled(false);
        c_for_nome.setEnabled(false);
        c_for_endereco.setEnabled(false);
        c_for_cidade.setEnabled(false);
        c_for_telefone.setEnabled(false);
    }//GEN-LAST:event_btn_for_cancelarActionPerformed

    private void btn_for_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_for_editarActionPerformed
        if(tbl_fornecedores.getSelectedRow() != -1){
            Fornecedor f = new Fornecedor();
            FornecedorDAO fdao = factory.getFornecedorDAO();
            
            f.setNome(c_for_nome.getText());
            f.setEndereco(c_for_endereco.getText());
            f.setCidade(c_for_cidade.getText());
            f.setTelefone(c_for_telefone.getText());
            
            f.setId((int)tbl_fornecedores.getValueAt(tbl_fornecedores.getSelectedRow(), 0));

            fdao.update(f);

            c_for_nome.setText("");
            c_for_endereco.setText("");
            c_for_cidade.setText("");
            c_for_telefone.setText("");

            readJTableFor();

            btn_pro_excluir.setEnabled(false);
            btn_pro_editar.setEnabled(false);
            btn_pro_cancelar.setEnabled(false);
            c_pro_nome.setEnabled(false);
            c_for_endereco.setEnabled(false);
            c_for_cidade.setEnabled(false);
            c_for_telefone.setEnabled(false);

        }else{
            JOptionPane.showMessageDialog(null, "Selecione um fornecedor para ser editado!");
        }
    }//GEN-LAST:event_btn_for_editarActionPerformed

    private void btn_for_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_for_novoActionPerformed
        c_for_nome.setText("");
        c_for_endereco.setText("");
        c_for_endereco.setText("");
        c_for_telefone.setText("");

        btn_for_salvar.setEnabled(true);
        btn_for_cancelar.setEnabled(true);
        c_for_nome.setEnabled(true);
        c_for_endereco.setEnabled(true);
        c_for_cidade.setEnabled(true);
        c_for_telefone.setEnabled(true);
        btn_for_editar.setEnabled(false);
    }//GEN-LAST:event_btn_for_novoActionPerformed

    private void btn_for_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_for_excluirActionPerformed
        if(tbl_fornecedores.getSelectedRow() != -1){
            Fornecedor f = new Fornecedor();
            FornecedorDAO fdao = factory.getFornecedorDAO();

            f.setId((int)tbl_fornecedores.getValueAt(tbl_fornecedores.getSelectedRow(), 0));

            fdao.delete(f);

            c_for_nome.setText("");
            c_for_endereco.setText("");
            c_for_cidade.setText("");
            c_for_telefone.setText("");

            readJTableFor();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um fornecedor para ser excluído!");
        }

        c_for_nome.setEnabled(false);
        c_for_endereco.setEnabled(false);
        c_for_cidade.setEnabled(false);
        c_for_telefone.setEnabled(false);
        btn_for_salvar.setEnabled(false);
        btn_for_cancelar.setEnabled(false);
        btn_for_editar.setEnabled(false);
        btn_for_excluir.setEnabled(false);
        btn_for_novo.setEnabled(true);
    }//GEN-LAST:event_btn_for_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cat_cancelar;
    private javax.swing.JButton btn_cat_editar;
    private javax.swing.JButton btn_cat_excluir;
    private javax.swing.JButton btn_cat_salvar;
    private javax.swing.JButton btn_for_cancelar;
    private javax.swing.JButton btn_for_editar;
    private javax.swing.JButton btn_for_excluir;
    private javax.swing.JButton btn_for_novo;
    private javax.swing.JButton btn_for_salvar;
    private javax.swing.JButton btn_fun_novo;
    private javax.swing.JButton btn_pro_cancelar;
    private javax.swing.JButton btn_pro_editar;
    private javax.swing.JButton btn_pro_excluir;
    private javax.swing.JButton btn_pro_novo;
    private javax.swing.JButton btn_pro_salvar;
    private javax.swing.JTextField c_cat_des;
    private javax.swing.JTextField c_cat_nome;
    private javax.swing.JTextField c_for_cidade;
    private javax.swing.JTextField c_for_endereco;
    private javax.swing.JTextField c_for_nome;
    private javax.swing.JTextField c_for_telefone;
    private javax.swing.JComboBox<Object> c_pro_categoria;
    private javax.swing.JComboBox<Object> c_pro_fornecedor;
    private javax.swing.JTextField c_pro_nome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tbl_categorias;
    private javax.swing.JTable tbl_fornecedores;
    private javax.swing.JTable tbl_produtos;
    // End of variables declaration//GEN-END:variables
}
